function RR1 = getHG_Tform(T,G,P)
%GETHG_TFORM
%    RR1 = GETHG_TFORM(T,G,P)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    03-Jun-2015 15:11:58

cG = cos(G);
sP = sin(P);
cP = cos(P);
sG = sin(G);
cT = cos(T);
sT = sin(T);
RR1 = reshape([cG.*cP,    sP.*cT+cP.*sG.*sT,     sP.*sT-cP.*sG.*cT,    -cG.*sP,    cP.*cT-sP.*sG.*sT,    cP.*sT+sP.*sG.*cT,     sG,        -cG.*sT,     cG.*cT],[3, 3]);
